/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Lista;
import Grafo.Grafo;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar
 */
public class Agregar extends javax.swing.JFrame {
    
    public static ModificarGrafo v3;
    static private Grafo grafo;
    static private File archivo;

    /**
     * Creates new form Agregar
     */
    public Agregar(ModificarGrafo v3, Grafo grafo, File archivo) {
        initComponents();
        this.v3=v3;
        v3.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.grafo=grafo;
        this.archivo=archivo;
    }
    
    public static Grafo getGrafo() {
        return grafo;
    }

    public static void setGrafo(Grafo grafo) {
        Agregar.grafo = grafo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NumeroCiudad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RelacionesCiudad = new javax.swing.JTextField();
        AgregarCiudad = new javax.swing.JButton();
        Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresa el numero de la ciudad:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 270, -1));

        NumeroCiudad.setBackground(new java.awt.Color(255, 153, 153));
        NumeroCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(NumeroCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 370, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese la ciudad, conexión y distancia entre ambas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        RelacionesCiudad.setBackground(new java.awt.Color(255, 153, 153));
        RelacionesCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelacionesCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(RelacionesCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 370, -1));

        AgregarCiudad.setBackground(new java.awt.Color(0, 0, 0));
        AgregarCiudad.setText("Agregar");
        AgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 80, -1));

        Menu.setBackground(new java.awt.Color(0, 0, 0));
        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumeroCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCiudadActionPerformed

    private void RelacionesCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelacionesCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelacionesCiudadActionPerformed

    private void AgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCiudadActionPerformed
        String numero_ciudad = NumeroCiudad.getText();
        String relaciones = RelacionesCiudad.getText();
        String[]relaciones2=relaciones.split(",");
        Lista lista=new Lista();
        if (relaciones.equalsIgnoreCase("")){
            
        }else{
            for(int i=0; i<relaciones2.length;i++){
            lista.insertFinal(relaciones2[i]);
            }
        }
        try{
        getGrafo().nuevoCiudad(numero_ciudad,lista);
        }catch(Exception err){
                JOptionPane.showMessageDialog(null, "No se ha cargado ningun archivo");
        }
    }//GEN-LAST:event_AgregarCiudadActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        Menu menu = new Menu(grafo,archivo);
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar(v3,grafo,archivo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCiudad;
    private javax.swing.JButton Menu;
    private javax.swing.JTextField NumeroCiudad;
    private javax.swing.JTextField RelacionesCiudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
